### ISSUE TITLE
Cannot add short domain?

### ISSUE THREAD

**Issue by leonguyen52** [towfiqi/serpbear#1]
Hi, I just tried to deploy on my vps. It installed successfully but when I'm trying to monitor a domain with 2 character (xx.com) but it doesn't allow me to add. Can you help to take a look?

**Comment by towfiqi** [comment]
Fixed. Thanks for catching the bug ;)

**Comment by leonguyen52** [comment]
Thank you! Will let you know if I find another one (hopefully not) 😆
