### ISSUE TITLE
Configure default country

### ISSUE THREAD

**Issue by thomas-mc-work** [towfiqi/serpbear#101]
It would be nice to have an option to define the default country. Like that in `docker-compose.yml`:

    environment:
      DEFAULT_COUNTRY: germany

I think many users have national related website which ranking results are mostly relevant in the same country.

**Comment by saschafoerster** [comment]
Would be very helpful to save clicks at the start.

**Comment by saschafoerster** [comment]
@towfiqi Thank you, works like a charm.
