### ISSUE TITLE
Feature request: Allow sorting of Keywords

### ISSUE THREAD

**Issue by saschafoerster** [towfiqi/serpbear#103]
Some keywords are more important to me, others are secondary. I would like to sort the keywords manually so I can scroll from important to not-so-important. 
Maybe additionally other sorting options would be nice as well: 
- Mobile/Desktop
- A-Z // Z-A
- Ranking/Position (up/down)
- Country

**Comment by towfiqi** [comment]
You can already do that with the Favorite feature. Click the 3 dots beside each item and click Favorite item and it will stick to the top of the list.

You can already sort the keywords, Alphabetically and ranking position. Click the sort icon from the top right corner of the keywords table to access the sorting options.
