### ISSUE TITLE
Integrate ValueSerp 

### ISSUE THREAD

**Issue by jagdish1o1** [towfiqi/serpbear#105]
Please integrate valueserp api, it's the most cheapest available. 

I'm facing issues with the free options.

**Comment by rogerserper** [comment]
Hey @jagdish1o1, you might want to check out https://serper.dev as well! We're even cheaper (and much faster) than ValueSerp.

**Comment by uhlhosting** [comment]
@rogerserper yes but serper have not been yet added to SerpBear.
