### ISSUE TITLE
Subdomain with dash not being tracked

### ISSUE THREAD

**Issue by Christian-Schou** [towfiqi/serpbear#107]
Hi

I have added my domain `xx.dk`, but then I have a blog on `blog.xx.dk` as a subdomain. 

How can I make SerpBear track the results on my subdomains? I can see my blog site shows up in the list of results, but SerpBear is not showing its position. When I try to enter the subdomain as a domain in SerpBear I'm told that it's not a valid domain.

Thanks in advance  ✌️

**Comment by towfiqi** [comment]
@Christian-Schou Just added both you domains to my serpbear instance and it was added fine. Then added the keyword "xx.dk" and it tracked fine. Can you give it a try again?

**Comment by Christian-Schou** [comment]
Hi @towfiqi 👋

Just pulled the latest version of the docker image and redeployed the application, but I still encounter the same issue. When I try to add my subdomain, I get an error, like the one below. I tried adding blog.xx.dk and that works fine, but a domain with a dash inside gives an invalid error.

![Serpbear add domain](https://i.gyazo.com/018f3dd183dd6dbd7c2d3f4e17329cbf.png)

**Comment by towfiqi** [comment]
Fixed in c0470cfa9d0dac86317c886065b461cfe82ffb16

**Comment by Christian-Schou** [comment]
Awesome! Thank you @towfiqi 😃
