### ISSUE TITLE
Search Console API Error:  403 Forbidden

### ISSUE THREAD

**Issue by joepolask86** [towfiqi/serpbear#108]
Why am I getting this error when integrating the Google search console? Followed the steps exactly.

[start] [ERROR] Search Console API Error for domain.com (30days) :  403 Forbidden
[start] [ERROR] Search Console API Error for domain.com (3days) :  403 Forbidden
[start] [ERROR] Search Console API Error for domain.com (30days) :  403 Forbidden
[start] [ERROR] Search Console API Error for domain.com (7days) :  403 Forbidden
[start] [ERROR] Search Console API Error for domain.com (30days) :  403 Forbidden
[start] [ERROR] Search Console API Error for domain.com (30days) :  403 Forbidden

Running on locally and fly.io. Still the same issue.

Could Not fetch Keyword Data for this Domain from Google Search Console.

**Comment by joepolask86** [comment]
Fixed it myself. Thanks

**Comment by sayem314** [comment]
@joepolask86 how did you fix it?

**Comment by demaya** [comment]
@joepolask86 how? :)

**Comment by sayem314** [comment]
Thanks @PaoloPC

Already fixed it a while ago somehow and I don't remember what I did to fix

**Comment by tvortex** [comment]
Hi,

Im having this same issue.
All websites setup on GSC as Domain work fine.
All websites setup on GSC as URL Prefix do not work.

Is this normal? If yes, is it a limitation and it is what it is. Or a fix will be made on a future update?

Thanks
