### ISSUE TITLE
[BUG] Reload All Serps feature not work

### ISSUE THREAD

**Issue by dazhiyu0235** [towfiqi/serpbear#109]
I have to click on each keyword individually or it won't update the data.

**Comment by mattzipan** [comment]
me too

**Comment by towfiqi** [comment]
Which scraper are you guys using?

**Comment by mattzipan** [comment]
SpaceSerp

**Comment by towfiqi** [comment]
@mattzipan I am also use spaceserp . The refresh all button is working fine for me. Although its quite slow. 
How many keywords did you add?

**Comment by mattzipan** [comment]
@towfiqi thanks for your feedback and all your work here. 

- I added roughly ~100 KWs.
_ I've been looking at the fly.io logging/monitoring: The app is restarted randomly every now and then, which of course cancels the update process.
- I followed the tutorial for fly.io for setup
- here screenshot:
![image](https://github.com/towfiqi/serpbear/assets/21261143/eae7f31d-7721-4084-87e6-ed663565c764)

**Comment by mattzipan** [comment]
update: The 'reload all serps' button works locally. So this must really be related to fly.io. - it's not a bug in the code.
