### ISSUE TITLE
[BUG] The Discover and Insight data does not get updated.

### ISSUE THREAD

**Issue by dazhiyu0235** [towfiqi/serpbear#110]
The data from Discover and Insight stays static from the day of integration and does not get refreshed daily.

**Comment by lostrockets** [comment]
same issue for me

**Comment by towfiqi** [comment]
Are you guys seeing any errors anywhere?

**Comment by lostrockets** [comment]
im not
ᐧ

**Comment by dazhiyu0235** [comment]
No error display

**Comment by towfiqi** [comment]
Ok. Upon close inspection. It looks like a bug. Will release a new version soon which should fix this issue.

**Comment by towfiqi** [comment]
Fixed in version 0.3.0
