### ISSUE TITLE
Keywords with special characters

### ISSUE THREAD

**Issue by jkawka** [towfiqi/serpbear#113]
The problem occurs when special characters are used in keywords, e.g. Polish characters
Examples:
- płytki ceramiczne
- kołobrzeg
- coś

`Error Updating Keyword position (Tried 10 minutes ago)
Scrapingrobot: Page loading error. Can not open the site`

**Comment by mishop** [comment]
The same problem is with Cyrillic characters.

**Comment by mishop** [comment]
I found problem
https://github.com/towfiqi/serpbear/blob/main/scrapers/services/scrapingrobot.ts
encodeURI not working properly, maybe need been encodeURIComponent()
When I encode keyword with https://www.urlencoder.org/ crawler working normally
<img width="1069" alt="Screenshot 2023-09-04 at 20 51 19" src="https://github.com/towfiqi/serpbear/assets/816233/fd5caa3e-21ef-4d11-9684-e1ee3277999e">
.

**Comment by OlliZabal** [comment]
I do have 2 entries producing the same error "Error Updating Keyword position Scrapingrobot: Page loading error. Can not open the site"
Language of the keyword phrases is German. But thoose two entries do have no special characters.
I got no clue, why I receive these two errors.
