### ISSUE TITLE
I can't update the positions

### ISSUE THREAD

**Issue by gengituser** [towfiqi/serpbear#116]
One day, I ran out of limits on the ScrapingRobot API and the data collection stopped. After 3 days, I added a new API key and restarted the collection of positions, but the data did not appear. I went to the docker logs and saw that the API data was being received, but for some reason, I only see this in the web interface: 

https://i.imgur.com/IaZQJnE.png

Real time logs:

https://i.imgur.com/mgjbcdT.png

Here is some error, maybe it's the reason. But it appears after some time, I don't know why and when:

https://i.imgur.com/U5T9r2D.png

And for some reason, I have a limited number of integrations in my settings:

https://i.imgur.com/o8G3jkX.png

I restarted the service via docker compose up, but no new integrations appear.

Could you please help me?

**Comment by towfiqi** [comment]
Sorry for the late reply. Try removing the `failed_queue.json` file inside the `data` folder.
