### ISSUE TITLE
Enhancement Request: Allow us to search local searches

### ISSUE THREAD

**Issue by DavidMoffatt1** [towfiqi/serpbear#117]
Instead of picking just a country it would be nice to be able to specify a city.

**Comment by towfiqi** [comment]
To scrape city-specific Google search results you need city-specific IP addresses. 
It's not possible because most scrapers/proxies only provide country-level IP addresses to scrape pages, they do not have city-specific IP addresses.

**Comment by towfiqi** [comment]
This has been added in v1.0.0 which has just been released. You can now scrape city-level Google search results with the following scrapers:

searchapi.io
serpapi.com
serper.dev
spaceserp.com
valueserp.com
