### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by thomas-mc-work** [towfiqi/serpbear#123]
Hello @towfiqi,

thank you for this project and all your efforts! This project seems to be very useful for a lot of people (almost 1k stars as of now). I've just noticed that there haven't been any contribution to the code since March 29. Neither directly nor via accepting pull requests. Accordingly, I'm asking myself about your plans about the project. Do you intend to continue the work on it? Or would it be possible to hand it over to a group of people who can take care of it? From my side it would be wonderful to know about a sustainable future of the project.

Thanks!
Thomas

**Comment by towfiqi** [comment]
I am kinda busy with another project currently. But I plan on updating the project every few months.  I plan on pushing the next update next month.

**Comment by thomas-mc-work** [comment]
Thank you for the clarification!

**Comment by SkyYap** [comment]
> I am kinda busy with another project currently. But I plan on updating the project every few months. I plan on pushing the next update next month.

Hi, do you think of getting maintainer in to continue updating this repo?
