### ISSUE TITLE
v0.3.0 unable to set Scraping Method besides "None"

### ISSUE THREAD

**Issue by sebastianseidel** [towfiqi/serpbear#126]
Did a clean start with v0.3.0

1. Created a domain
2. Try setting a "Scraping Method"
3. Only available option is "None"

![Screenshot 2023-11-04 at 16 48 56](https://github.com/towfiqi/serpbear/assets/14950853/07a8eb1f-a136-49df-b4e8-8cbf7abb58de)

**Comment by towfiqi** [comment]
Fixed in v0.3.1 4620f11c4b844a4aa0adde77c6b21d52010e6d80
