### ISSUE TITLE
Domain Position is not shown when its the first result

### ISSUE THREAD

**Issue by towfiqi** [towfiqi/serpbear#13]
I don't know if it's same issue, but on my side : 
I've added the domain https://sucrine.club (from France), which is first with keyword "Sucrine club" and position is not displayed on dashboard.

_Originally posted by @lionep in https://github.com/towfiqi/serpbear/issues/6#issuecomment-1334035655_

**Comment by lionep** [comment]
Thanks, I didn't try with other country, but here is the response from scrapingant api

[scraping-ant-response.txt](https://github.com/towfiqi/serpbear/files/10139402/scraping-ant-response.txt)

**Comment by towfiqi** [comment]
Thanks. Yes I already figured out the bug and will fix it shortly.
