### ISSUE TITLE
domain thumb empty

### ISSUE THREAD

**Issue by bilyboy785** [towfiqi/serpbear#131]
Hi ! 

What is the purpose of domain thumb, on my self hosted installation, i've got an image with "this account is curently frozen".

**Comment by bilyboy785** [comment]
It's seem's that your account is frozen on image.thum.io.

Ex : https://image.thum.io/get/auth/66909-serpbear/maxAge/96/width/200/https://www.bldwebagency.fr

**Comment by towfiqi** [comment]
yes. In the next version, you will be able to insert your own thum.io key.

**Comment by saschafoerster** [comment]
I would even prefer not to go via a third party, but there must be a good reason, why you not use favicon.ico or similar? Maybe it could be an option to first use the existing favicon if people don't use thum.io, but if the enter a key, the get the images from there?

**Comment by towfiqi** [comment]
Yeah, I have implemented just that. Will release the next version shortly.
I prefer the screenshot because it looks better. Not all websites have the same size favicon which makes the UI look a little inconsistent.
