### ISSUE TITLE
Not working? Using ScrapingAnt Api

### ISSUE THREAD

**Issue by daXenlo** [towfiqi/serpbear#135]
It seems like theres an issue with the ScrapingAnt imlemention.
I've just set up my API Key with my premium ScrapingAnt Account and added a Domain. Tested 10 Keywords in a country that my website ranks for in top 5-30 and all results are >100.

**Comment by SebastjanPrachovskij** [comment]
Hey @daXenlo 

I have recently added SearchApi support to SerpBear and I am running it myself without issues. Maybe it would help.

**Comment by towfiqi** [comment]
@daXenlo Can you please check the log? 

FYI, ScrapingAnt disabled google scraping for the free accounts a few months ago. Not sure if they also did it for the paid account as well.
