### ISSUE TITLE
Found page and SERP results not listed for keyword

### ISSUE THREAD

**Issue by dreadedhamish** [towfiqi/serpbear#136]
I'm not sure if this is a temporary issue or not.

I've got a keyword that has a ranking number, but no URL listed:
https://ibb.co/M8ncDwf

When viewing the search results it only shows the first 2 results:
https://ibb.co/VqC89Mp

**Comment by dreadedhamish** [comment]
More weird results - 
A tracked keyword - Rank 83 (down 3) - best blank (there are historical records though) - Ranking page - blank. Not actaully in the top 100 (according to the cached results.
I'm a bit new here - has best ever worked?

**Comment by towfiqi** [comment]
Something is not right in your instance. Can you please get in touch through this form about this issue? https://f.nativeforms.com/wNShVbD1jZmQVQmBlWL1Db

**Comment by dreadedhamish** [comment]
> Something is not right in your instance. Can you please get in touch through this form about this issue? https://f.nativeforms.com/wNShVbD1jZmQVQmBlWL1Db

I won't lie - I've moved the database around abit and might have messed it up. I've just done a clean install - I'll watch it closely for this behaviour. I was only one project I noticed it on.
