### ISSUE TITLE
Feature Request: Local Targeting Search - Geo Location

### ISSUE THREAD

**Issue by Biztactix-Ryan** [towfiqi/serpbear#139]
I'd love to see it able to provide GeoTargeting on both Mobile and Desktop.... That would make it useful for brick and mortar shops, not just online companies

Just down to a Town Level would be fine.... But some companies provide Lat/Long to test mobile search.

**Comment by b6user** [comment]
Agree, be a great feature.

**Comment by jkdn0921s** [comment]
I'd love as well to see this feature, using now Scraping Robot.

It'd be great to see city in addition to just the country:

![serpbear local](https://github.com/towfiqi/serpbear/assets/139198315/1ea4c7c3-0da9-46ee-9c60-d43cbc00915e)

Thank you!

**Comment by wrtz008** [comment]
Agree too, it'd be awesome to see this feature, thank you so much!

**Comment by s3w47m88** [comment]
I agree. I am going to have my programming staff look into developing a patch for this.

**Comment by towfiqi** [comment]
@s3w47m88 I will actually start working on it myself within the next few days.

**Comment by d363f86b** [comment]
Thank you @towfiqi - I will stand by then. But let me know if you'd like us to assist.

**Comment by s3w47m88** [comment]
Thank you @towfiqi  - I will stand by then. But let me know if you'd like us to assist.

**Comment by jkdn0921s** [comment]
you guys rock, thanks for working on this, super appreciated!

**Comment by towfiqi** [comment]
This has been added in v1.0.0 which has just been released. You can now scrape city-level Google search results with the following scrapers:

searchapi.io
serpapi.com
serper.dev
spaceserp.com
valueserp.com

**Comment by Ryan12439** [comment]
Hi! I appreciate this addition, and wanted to add in my two cents. Google has a UULE perimeter on the URL you can add, which allows you to specify a location (city, coordinates, etc). This could be used on the scrapers that do not natively have the functionality built in. I have included JS code on how I implemented this in my own app, I do not have any experience with TS or this codebase unfortunately, but it is relatively simple:

`    <script>
        function lengthBit(n) {
            var bits = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
            return bits[n % 64];
        }

        function encode(loc) {
            var lenBit = lengthBit(loc.length);
            return 'w+CAIQICI' + lenBit + btoa(loc);
        }

        function createSearchURL(query, loc) {
            var encodedLoc = encode(loc);
            return 'https://www.google.com/search?q=' + encodeURIComponent(query) + '&uule=' + encodedLoc;
        }

        function generateURL() {
            var query = document.getElementById('query').value;
            var loc = document.getElementById('loc').value;
            var url = createSearchURL(query, loc);
            
            document.getElementById('result').innerHTML = 'Generated URL: <a href="' + url + '" target="_blank">' + url + '</a>';
            return false; // Prevent form submission
        }
    </script>
`

**Comment by s3w47m88** [comment]
Where does this new setting appear? I pulled the latest via Docker and I don't see any options, I also don't see ValueSERP listed in the drop down.

**Comment by towfiqi** [comment]
> Where does this new setting appear? I pulled the latest via Docker and I don't see any options, I also don't see ValueSERP listed in the drop down.

Did you update your serpbear instance? How are you running the app via docker or running locally without docker?

**Comment by d363f86b** [comment]
Docker. Yeah I am on Windows and opened PowerShell ans pulled the latest
successfully.

--
[image: logo] <http://www.theportlandcompany.com/> Spencer Hill
Principal • The Portland Company
mobile: (503) 610-8759 • office: (503) 567-9561
www.ThePortlandCompany.com <http://www.theportlandcompany.com/>
Advertising | Search | Social | Websites | Integrations | Apps |
Photography | Film | Multimedia

**Comment by towfiqi** [comment]
What command did you use to pull the latest release? Did you try restarting your container?

**Comment by d363f86b** [comment]
Yep. `docker pull towfiqi/serpbear:latest`

--
[image: logo] <http://www.theportlandcompany.com/> Spencer Hill
Principal • The Portland Company
mobile: (503) 610-8759 • office: (503) 567-9561
www.ThePortlandCompany.com <http://www.theportlandcompany.com/>
Advertising | Search | Social | Websites | Integrations | Apps |
Photography | Film | Multimedia

**Comment by d363f86b** [comment]
Any thoughts? Could you share a screenshot of what users should see to
choose a location?

--
[image: logo] <http://www.theportlandcompany.com/> Spencer Hill
Principal • The Portland Company
mobile: (503) 610-8759 • office: (503) 567-9561
www.ThePortlandCompany.com <http://www.theportlandcompany.com/>
Advertising | Search | Social | Websites | Integrations | Apps |
Photography | Film | Multimedia

**Comment by towfiqi** [comment]
You should see a new City field in the Add Keyword Modal.
![Screenshot 2024-02-13 231822](https://github.com/towfiqi/serpbear/assets/1926614/9761c0a9-7790-4894-b834-86745079c080)

After pulling the latest docker image, did you run the container from the latest image?

**Comment by s3w47m88** [comment]
Thank you. You can close this Ticke now.

For those who might experience this issue as well:

It was my mistake (I'm new to Docker). I had three Images, two were "Dangling" (not associated with a Container) So when I ran the Pull command in PowerShell, to update SERPBear, it was updating one of the Dangling ones instead of the one associated with the Container.

I used ChatGPT to help me debug this.

Sent with [Proton Mail](https://proton.me/) secure email.
