### ISSUE TITLE
User and Pasword always invalid

### ISSUE THREAD

**Issue by vivacoda** [towfiqi/serpbear#14]
hello i follow the step for Running SerpBear Locally
Fresh install
i add .env.local copy past of the ex. no change and i can't login

**Comment by towfiqi** [comment]
Are you using docker or are you pulling the source from github [directly](https://docs.serpbear.com/deployment/running-serpbear-locally) ?

**Comment by vivacoda** [comment]
Thanks from github directly

**Comment by vivacoda** [comment]
.env.local
 
`USER=admin
PASSWORD=0123456789
SECRET=4715aed3216f7b0a38e6b534a958362654e96d10fbc04700770d572af3dce43625dd
APIKEY=5saedXklbslhnapihe2pihp3pih4fdnakhjwq5
SESSION_DURATION=24
NEXT_PUBLIC_APP_URL=http://localhost:3000`

**Comment by vivacoda** [comment]
Same issue with docker
<img width="922" alt="Screenshot 2022-12-02 at 11 26 15" src="https://user-images.githubusercontent.com/75243836/205214725-33dde46a-b5b3-4a84-97e1-86596e2f3ca8.png">
<img width="1461" alt="Screenshot 2022-12-02 at 11 26 11" src="https://user-images.githubusercontent.com/75243836/205214728-72166fbc-8dc1-4af9-a0f4-e3630ed5d646.png">

**Comment by vivacoda** [comment]
Solved fly.io was running ... Thanks
