### ISSUE TITLE
Error Adding New Domain

### ISSUE THREAD

**Issue by HarshBhardwaj** [towfiqi/serpbear#142]
![ErrorAddingDomain](https://github.com/towfiqi/serpbear/assets/12777116/9ddb18e7-a671-4a01-aa55-400f25d318e4)

After following instruction from [this](https://pimylifeup.com/raspberry-pi-serpbear/) article, I signed up for robot service and got my API key. I used that API Key when I was selecting the service in settings age of the UI. I tried to add a new domain (one of my site) and I keep on getting the following error in console.

**Comment by towfiqi** [comment]
does your domain have any special character? can you please share your domain address?

**Comment by HarshBhardwaj** [comment]
No special characters or anything. Domain I was using for testing was (https://dogoverbreed.com)

**Comment by towfiqi** [comment]
Can you please try restarting your SerpBear instance?
