### ISSUE TITLE
Adding multiple Google Search Console private keys and emails on PikaPods

### ISSUE THREAD

**Issue by jkdn0921s** [towfiqi/serpbear#146]
I am using [PikaPods](https://www.pikapods.com) for deploying the app and was wondering if it'd be possible to add multiple Google Search Console keys and emails on it?

I tried adding it in the settings, but per each Pod there is only 1 x Search Console private key and email.

![multiple GSC accts different emails](https://github.com/towfiqi/serpbear/assets/139198315/d09af411-1c95-46f6-acad-3678264153d1)

If we have different websites, each with their own Gmail account and separate Search Console private keys and emails, is there any way to add them in the same Pika Pod?

Thank you!

**Comment by towfiqi** [comment]
@jkdn0921s Sorry, not possible currently. In a future release, will add the GSC API input UI in the Domain Settings Panel, so that those API keys/email override the global one.

**Comment by jkdn0921s** [comment]
> @jkdn0921s Sorry, not possible currently. In a future release, will add the GSC API input UI in the Domain Settings Panel, so that those API keys/email override the global one.

thanks for the reply! 

cool, that means that the GSC API will allow for unlimited ones to be added I guess?

**Comment by towfiqi** [comment]
v1.0.0 has been released with this feature. You can now setup domain level GSC from the Domain Settings Modal.
![Screenshot 2024-02-09 221528](https://github.com/towfiqi/serpbear/assets/1926614/0aa99bcc-bcb3-4b38-88e7-5fc7a53b5564)

**Comment by jkdn0921s** [comment]
sweeeet! thank you!
