### ISSUE TITLE
Add subdomains to SerpBear and Insight section

### ISSUE THREAD

**Issue by wrtz008** [towfiqi/serpbear#148]
Is it possible to add the subdomains to SerpBear as separate domains,, i.e. https://domain.com and https://www.domain.com including seeing the data separate in Insight?

We'd like to track the data separate per each subdomain and currently we can only add the root domain when adding a domain.

The data we see in Insight from Google Search Console is only from the root domain (which is combined from all subdomains).

Thank you!

**Comment by towfiqi** [comment]
You can add any subdomain but not with the `www`. Try adding any other subdomains and it should work.

As for Google Search Console integration, currently, it only works for domain-level properties. Google Search console allows you to add 2 types of domains, domain level, which consists of domain and subdomains. The other is URL level, which allows you to add websites hosted in a subdirectory. eg: https://test.com/test. Currently, SerpBear only supports domain-level properties. If you are not getting the search console data for a certain domain in SerpBear, make sure it's a domain-level property.

**Comment by wrtz008** [comment]
> You can add any subdomain but not with the `www`. Try adding any other subdomains and it should work.

I tried adding subdomains as https://domain.com but it's not working, maybe it's just my case?
I am using Pikapods to run the SerpBear app.
Every time I try to add these subdomains I get an error "Not a Valid Domain"

> As for Google Search Console integration, currently, it only works for domain-level properties. Google Search console allows you to add 2 types of domains, domain level, which consists of domain and subdomains. The other is URL level, which allows you to add websites hosted in a subdirectory. eg: https://test.com/test. Currently, SerpBear only supports domain-level properties. If you are not getting the search console data for a certain domain in SerpBear, make sure it's a domain-level property.

We have the domains added in GSC at domain level, all have TXT record verifications. Most of the domains we have are 'www' subdomains. That means if we can't add the 'www' subdomain, then seeing GSC data for them won't work anyway because we can't add them.

Do you think you will be able to add the 'www' subdomains in the future too? 
That'd be amazing!

Thank you!

**Comment by wrtz008** [comment]
> > I tried adding subdomains as https://domain.com/ but it's not working, maybe it's just my case?
> 
> https://domain.com/ is not a subdomain. Do you mean you tried adding https://www.domain.com/ and got that error message? Try adding only the domain: `domain.com`. Everything should work fine.

Yes, you are correct, https://domain.com is not a subdomain.

I tried adding both https://www.domain.com/ and https://domain.com/ and got that error message.
I see what you mean, I can add any subdomains like https://abc.domain.com/ but not the https://www.domain.com/

I did add domain.com and it works but the problem is that we sometimes have the 'www' subdomain as the main one and wanted to differentiate the,

I understand if adding 'www' is not possible.

> As for the GSC integration, yes it should pull the data, regardless of the `www`.

Yes, that's what I wanted to differentiate in GSC the data from 'www' separate than the root domain 'domain.com'
