### ISSUE TITLE
Explanation of how rankings are confirmed?

### ISSUE THREAD

**Issue by s3w47m88** [towfiqi/serpbear#154]
I am brand new to SERPBear and successfully launched it with ease via Docker and ScrapingAnt. But it's reporting 100% of the keywords for all 3 domains I've added so far are appearing below 100. But a simply Google search shows that's largely innaccurate with many keywords ranking in the top 10, 5 and 3.

Can anyone provide inside as to how SERPBear is getting these rankings precisely?

**Comment by towfiqi** [comment]
What service are you using to scrape the ranking?

**Comment by towfiqi** [comment]
Yes. You have to bring your own Google scraper. 
ScrapingAnt doesn't work anymore as they have stopped allowing free users to scrape Google with their service. You can use another scraper. Following scraper integrations are available in Serpbear:
https://docs.serpbear.com/integrations

**Comment by s3w47m88** [comment]
Oh even with the paid version? I paid for that which isn't a big deal but I am surprised they didn’t communicate that.

**Comment by towfiqi** [comment]
I just found their old email that detailed the Google scraping change. 

> Google Requests: Google has always been an important platform for data extraction. However, we have had to adjust the pricing for scraping Google data due to increased operating costs. Starting today, requests to Google without browser rendering will cost 10 API credits instead of the previous 1 API credit. We assure you that our service will continue to provide the same high-quality data as before, with the speed and accuracy you have come to expect.

Looks like it should work fine. You will probably have to ask them about the issue you are having. 
You can also give scrapingrobot a try. They have a decent free plan.

**Comment by s3w47m88** [comment]
Thanks, I switched to Scraping Robot and immediately got ranking results.
