### ISSUE TITLE
Build error on fly.dev

### ISSUE THREAD

**Issue by brunocantuaria** [towfiqi/serpbear#158]
I'm running SerpBear on fly.dev , but when trying to update, the process will stop on build process:

` => ERROR [builder 7/7] RUN npm run build                                                                         11.6s
------
 > [builder 7/7] RUN npm run build:
#0 0.931
#0 0.931 > serpbear@0.3.4 build
#0 0.931 > next build
#0 0.931
#0 1.553 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#0 1.554 This information is used to shape Next.js' roadmap and prioritize features.
#0 1.554 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 1.554 https://nextjs.org/telemetry
#0 1.554
#0 1.743 info  - Linting and checking validity of types...
#0 11.46 Failed to compile.
#0 11.46
#0 11.46 ./components/keywords/KeywordFilter.tsx:38:23
#0 11.46 Type error: This expression is not callable.
#0 11.46   Each member of the union type '{ (callbackfn: (previousValue: KeywordType, currentValue: KeywordType, currentIndex: number, array: KeywordType[]) => KeywordType): KeywordType; (callbackfn: (previousValue: KeywordType, currentValue: KeywordType, currentIndex: number, array: KeywordType[]) => KeywordType, initialValue: KeywordType): KeywordType; <U...' has signatures, but none of those signatures are compatible with each other.
#0 11.46
#0 11.46   36 |
#0 11.46   37 |    const keywordCounts = useMemo(() => {
#0 11.46 > 38 |       return keywords.reduce((acc, k) => ({
#0 11.46      |                       ^
#0 11.46   39 |          desktop: k.device === 'desktop' ? acc.desktop + 1 : acc.desktop,
#0 11.46   40 |          mobile: k.device !== 'desktop' ? acc.mobile + 1 : acc.mobile,
#0 11.46   41 |       }), { desktop: 0, mobile: 0 });
#0 11.51 npm notice
#0 11.51 npm notice New minor version of npm available! 10.2.4 -> 10.4.0
#0 11.51 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
#0 11.51 npm notice Run `npm install -g npm@10.4.0` to update!
#0 11.51 npm notice
------
Error: failed to fetch an image or build from source: error building: failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1`

Any clue?

**Comment by towfiqi** [comment]
this issue will be fixed in the next version, which should be released tomorrow.

**Comment by Yo-shad** [comment]
> this issue will be fixed in the next version, which should be released tomorrow.

Have the same problem

`PS C:\Users\ASUS\Documents\serpbear> npm run build    

> serpbear@0.3.4 build
> next build

 ⚠ Disabling SWC Minifer will not be an option in the next major version. Please report any issues you may be experiencing to https://github.com/vercel/next.js/issues
   ▲ Next.js 14.1.0
   - Environments: .env.local

   Linting and checking validity of types  .Failed to compile.

./components/keywords/KeywordFilter.tsx:38:23
Type error: This expression is not callable.
  Each member of the union type '{ (callbackfn: (previousValue: KeywordType, currentValue: KeywordType, currentIndex: number, array: KeywordType[]) => KeywordType): KeywordType; (callbackfn: (previousValue: KeywordType, currentValue: KeywordType, currentIndex: number, array: KeywordType[]) => KeywordType, initialValue: KeywordType): KeywordType; <U...' has signatures, but none of those signatures are compatible with each other.

  36 |
  37 |    const keywordCounts = useMemo(() => {
> 38 |       return keywords.reduce((acc, k) => ({
     |                       ^
  39 |          desktop: k.device === 'desktop' ? acc.desktop + 1 : acc.desktop,
  40 |          mobile: k.device !== 'desktop' ? acc.mobile + 1 : acc.mobile,
  41 |       }), { desktop: 0, mobile: 0 });`
