### ISSUE TITLE
Build error - Failed to compile 

### ISSUE THREAD

**Issue by Yo-shad** [towfiqi/serpbear#160]
### **Try to install locally but face this issue when : npm run build**

**ANY IDEA?**

`C:\Users\ASUS\Documents\serpbear>npm run build

> serpbear@0.3.4 build
> next build

 ⚠ Disabling SWC Minifer will not be an option in the next major version. Please report any issues you may be experiencing to https://github.com/vercel/next.js/issues
   ▲ Next.js 14.1.0
   - Environments: .env.local

   Linting and checking validity of types  .Failed to compile.

./components/keywords/KeywordFilter.tsx:38:23
Type error: This expression is not callable.
  Each member of the union type '{ (callbackfn: (previousValue: KeywordType, currentValue: KeywordType, currentIndex: number, array: KeywordType[]) => KeywordType): KeywordType; (callbackfn: (previousValue: KeywordType, currentValue: KeywordType, currentIndex: number, array: KeywordType[]) => KeywordType, initialValue: KeywordType): KeywordType; <U...' has signatures, but none of those signatures are compatible with each other.

  36 |
  37 |    const keywordCounts = useMemo(() => {
> 38 |       return keywords.reduce((acc, k) => ({
     |                       ^
  39 |          desktop: k.device === 'desktop' ? acc.desktop + 1 : acc.desktop,
  40 |          mobile: k.device !== 'desktop' ? acc.mobile + 1 : acc.mobile,
  41 |       }), { desktop: 0, mobile: 0 });`

**Comment by towfiqi** [comment]
Fixed in 633ab2c467be5b7b86d4547ae0c59034e595a42d
