### ISSUE TITLE
Incorrect Google Search Results (Screenshot Included)

### ISSUE THREAD

**Issue by s3w47m88** [towfiqi/serpbear#164]
![fe4ca679-f241-4667-b441-fa625e8d7179](https://github.com/towfiqi/serpbear/assets/656776/8cb621ff-91e4-4b90-96fd-88689caf0d05)

As you can see in this screenshot the visual presentation of search results is highlighting a domain that is not the domain being tracked.

**Comment by towfiqi** [comment]
Thanks for pointing it out. It was a bug.
