### ISSUE TITLE
Running Docker compose up but the app doesn't update to the newest version

### ISSUE THREAD

**Issue by dangson92** [towfiqi/serpbear#166]
Hi there

I run docker compose up command to update serpbear to newest version (I built it on ubuntu server)  but it's still showing version 0.3.4

What am I wrong?

**Comment by dangson92** [comment]
it's showing old version 0.3.4
![image](https://github.com/towfiqi/serpbear/assets/9291226/bab11817-ec7f-4760-a0f9-849e97fbf8ec)

**Comment by dangson92** [comment]
it's ok now, your instruction is missing. I need to run docker compose pull before re-run docker compose up

**Comment by towfiqi** [comment]
Thanks for your input. I have updated the docs.
