### ISSUE TITLE
Bug: Missing data get from scraping robot

### ISSUE THREAD

**Issue by dangson92** [towfiqi/serpbear#172]
Hi there, I have a trouble with data when get it via Scraping Robot API

![image](https://github.com/towfiqi/serpbear/assets/9291226/612f4948-1fc6-4275-8a1c-b4d4cfc492cc)

So, when I check around 800 keywords, 5% of them are missing (just showing only 2 result)

**Comment by towfiqi** [comment]
fixed the issue in version 1.0.3 which was released a few hours ago. Make sure you are using the updated version to resolve this issue.
