### ISSUE TITLE
After upgrade to 2.0 all Tracking keywords are empty.

### ISSUE THREAD

**Issue by graphiostudio** [towfiqi/serpbear#178]
As in the title, After upgrading to 2.0 all Tracking keywords are empty, just keep loading and then "No Keywords Added for this Device Type." but the domains page shows the summary of how many keywords for each domain correctly. What might be wrong?

**Comment by graphiostudio** [comment]
<img width="1100" alt="image" src="https://github.com/towfiqi/serpbear/assets/88828443/1c897a43-8178-494e-a6d2-a68bd55aaa9c">
<img width="1409" alt="Screenshot 2024-03-06 at 13 41 57" src="https://github.com/towfiqi/serpbear/assets/88828443/b12c484b-a7e6-4f22-8146-faa06dac0575">

Self-hosted on NAS, docker container, ports exposed... Everything was working up until the last update. Tried rebuilding and deploying, no changes.

**Comment by towfiqi** [comment]
Can you please check the container log and share if you find any error messages?

**Comment by graphiostudio** [comment]
getting this error:
<img width="717" alt="image" src="https://github.com/towfiqi/serpbear/assets/88828443/d9ba29e7-41f6-4673-b858-75ac3a579e89">

**Comment by Matthijz98** [comment]
I have the same error in my container.

**Comment by towfiqi** [comment]
Fixed in [v2.0.1](https://github.com/towfiqi/serpbear/releases/tag/v2.0.1)

**Comment by graphiostudio** [comment]
@towfiqi Thank you for the lightning-fast response and fixes. You rock!
