### ISSUE TITLE
npm run db:migrat on portainer

### ISSUE THREAD

**Issue by Plobli** [towfiqi/serpbear#191]
Hi,

i am running serpbear on my portainer as a docker. Today i update the container but than i lost all my data (domains, keywords etc.) But i noticed, that there is a message after login: 
`You need to Update your database. Stop Serpbear and run this command to update your database:npm run db:migrate
`
But i don't use npm, so what can i do to get my data back?

**Comment by towfiqi** [comment]
Usually, to update the docker instance to the latest version, you have to run `docker compose pull` and then `docker compose up`. maybe try running these commands with portainer?

**Comment by Plobli** [comment]
Ah, inside portainer i have to deploy the stack again, not only the container. That works. Thank you for your help and this nice piece of software.
