### ISSUE TITLE
[Feature] Add device type 'tablet' to assign keywords to / universal

### ISSUE THREAD

**Issue by CodeAlDente** [towfiqi/serpbear#199]
Currently, we have the capability to assign keywords for both desktop and mobile platforms. Extending this functionality to include tablets would be beneficial. Additionally, having the option to even specify a universal keyword that applies across all devices would be a valuable enhancement.

**Related issues:**
#66 Allow to add keywords both to pc and mobile

**Comment by towfiqi** [comment]
Adding a device-type tablet is not feasible as most scrapers do not have a tablet option.
