### ISSUE TITLE
[Improvement] Adjustments to notification emails

### ISSUE THREAD

**Issue by CodeAlDente** [towfiqi/serpbear#202]
Just some thoughts about the notification emails that came to my mind:

- [ ] Use a proven template, ref: https://github.com/leemunroe/responsive-html-email-template.
- [x] In the table, include information about the best position so far, similar to the dashboard.
- [ ] The value of the updated row should be the exact date instead of being relative because the email is stored "as seen."

**Comment by towfiqi** [comment]
The 2nd request has been added in [4c2f900](https://github.com/towfiqi/serpbear/commit/4c2f900d85e56b1994630942c9ea53d0fd0b4cdb)
