### ISSUE TITLE
[Bug] The keyword shows a position but the page isn't mine

### ISSUE THREAD

**Issue by sixtineio** [towfiqi/serpbear#206]
<img width="693" alt="screen-serpear-wrong-page" src="https://github.com/towfiqi/serpbear/assets/39901434/fa985e9a-39e2-42cf-89e4-2fd015c664d5">

Hi 😄 
It happens on few keywords but on different projects in my Serpbear environment.

**Comment by towfiqi** [comment]
Can you please share your domain/URL ?

**Comment by dangson92** [comment]
Sometime, I got this too

**Comment by JvB94** [comment]
same issue here also. Is someone still maintain Serpbear?

**Comment by chester-e** [comment]
same here. is serpbear still maintained? or does anyone know a good alternative.

**Comment by towfiqi** [comment]
I will look into it tonight.

**Comment by towfiqi** [comment]
@chester-e  Please share your domain/URL and the keyword so I can recreate the issue.

**Comment by JvB94** [comment]
@towfiqi thats not really easy to reproduce. You must add the keyword to your Serpbear then you need to wait until the keyword for that domain got ranked. The issue happend then when the keyword got unkranked again.

**Comment by towfiqi** [comment]
@JvB94 Thanks for the reply. Yes, you are correct. Had to dig through the code to figure out why I set that 0 condition. Looks like it was there to adopt an old condition that is no longer necessary. Will merge the PR now.
