### ISSUE TITLE
Position Tracking - Country and langage

### ISSUE THREAD

**Issue by sachatrauwaen** [towfiqi/serpbear#207]
Issue :
The used language is hardcoded by country.
And some coutries have multiple languages and Google search have also multiple languages by country with different search results for the same keyword.

Solution :
So "Position tracking" need not only by country but also by language.
For mono language website, it have sence to define a default language on the domain settings

Remarq : I have sean also that some SERP tracking services use already the hardcoded language by country but other not.

Enhancemant :
In will be easyer to restrict the country dropdown filter to the countries present in the keywords
For a website targeting only local people (mono country website) it can have sense to define a default country.

**Comment by towfiqi** [comment]
The enhancement suggested by you has been added in [a050536](https://github.com/towfiqi/serpbear/commit/a0505368140076d6626647993a41a5f4ef9db019)

**Comment by ta1kun** [comment]
is it ready this? i also need different language to search. for example i m searching in google.ch that is german hardcoded but i need to search in french
