### ISSUE TITLE
Outdated docs for Google Ads integration

### ISSUE THREAD

**Issue by tcurdt** [towfiqi/serpbear#209]
The docs state:

"Once the account is created, click the "Tools" button from the top and then click the "API Center" menu.

When the API Center page opens up, copy the "Developer token" go back to SerpBear's Google Ads Integration Settings panel, and insert it in the Developer token field."

...but there is no such thing.

![Screenshot 2024-05-05 at 00 23 08](https://github.com/towfiqi/serpbear/assets/13697/ab3f64d4-37e5-4153-bcce-61382b187f0e)

**Comment by towfiqi** [comment]
You have to create 2 AdWords accounts. One of them is a developer account. You can access the "API Center" inside the developer account area. Check the documentation again to learn how to create a developer account.

**Comment by tcurdt** [comment]
I guess that presumes the first account is a developer account?

![Screenshot 2024-05-05 at 15 15 49](https://github.com/towfiqi/serpbear/assets/13697/bff20c02-606b-4020-9564-9d05cdf2808f)

That wasn't quite so clear for me.

**Comment by towfiqi** [comment]
Yes, the first one is the developer account. You are probably logged in inside the Test account. You can switch the accounts, by clicking your profile image from the top right corner of the screen. Once you log in to your developer account, you should be able to access the "Tools and Settings" menu from the top right corner of the screen.

**Comment by tcurdt** [comment]
So far I only have a single account - the one I had before. No worries.
But I guess it would be good to add this to the documentation.

**Comment by ryanovas** [comment]
@tcurdt it's in the admin section now, not tools. The rest of the instructions seem to be correct, I was just able to get hooked up. But there are a few extra steps like creating the token. Also, when you click the button to create the test account it's gunna look the same as the manager account but you'll notice "test account" in red in the top corner. Just go with the flow.

**Comment by carsaig** [comment]
Heads-up: it works. Though it's very, very confusing for anyone not handling adwords accounts on a daily base to understand the account structure and all their detailed feature differences. It boils down to having a manager account in the first place, as described in the docs and then opening a test accound (which can go sideways, if one opens another manager account instead by mistake). It took me a few accounts to get it right, despite the correct link in the docs. No idea why I ended up with multiple manager accounts at first. However - having one manager account and one dev account cuts it. Works as described.

**Comment by tcurdt** [comment]
Google is such a mess. Thanks for the help. But I think I just let it be.
