### ISSUE TITLE
Keyword column too narrow

### ISSUE THREAD

**Issue by afanjul** [towfiqi/serpbear#224]
Hi, 
Could you please increase the width of the keyword column to avoid words truncation? 
I mean, the most important part of the report is to know what is the keyword you are positioning on 5th position, but if you have some keywords with the same beginning part, all the rows displays the same keyword part and it's quite annoying. 
Some ways to solve it:
- Remove the whitespace-nowrap class in keyword column (or add it but as an option toggle)
- Increase the keyword column width 
- Allow full width of the whole app interface
- Allow to select columns to display
- Allow increase/decrease font size
- Allow inner scroll in the table

Thanks

**Comment by djav1985** [comment]
I second this. also if you're using a location based serp checker you can't see the location if the key word is too long and it doesn't have to be that long to be too long. I think the location should maybe be on a line below the keyword

**Comment by chester-e** [comment]
+1
