### ISSUE TITLE
Error Saving the Google Ads Refresh Token . Details: redirect_uri_mismatch. Please Try Again!

### ISSUE THREAD

**Issue by alexionegit** [towfiqi/serpbear#225]
Hello dear friends,

I am unsuccessful in integrating SerpBear v 2.0.2 with Google Ads. The app is hosted on my personal server on a https subdomain proxied by Cloudflare.

I get the redurect_uri_mismatch error and if I refresh that page I get the invalid_grant error.

I have tried to have the Oath consent screen in test mode and as well as published.

I read and tried most of the fixes suggested on these pages.

NEXT_PUBLIC_APP_URL = Authorised redirect URIs in Google Cloud Platform, Credentials

I do not even know what to do next.

Could you please help me?

Thank you! @towfiqi

Alex

**Comment by kbkozlev** [comment]
I solved this by creating a new token and using it instead.
