### ISSUE TITLE
Not able to add domain when deployed deep war on my vps

### ISSUE THREAD

**Issue by swatigour2000** [towfiqi/serpbear#230]
Hi Towfiqi,

Recently, I deployed SerpBear on my VPS, following the documentation exactly as demonstrated. After successfully deploying it, I encountered an issue when trying to add a domain. The system displays an error message stating, "error adding new domain."

Is there a workaround for this?

P.S.: I am a newbie to Next.js development.

Thank you,

**Comment by hassanmirseo** [comment]
Has the issue been solved? I'm getting same issue

**Comment by swatigour2000** [comment]
Yes, actually you just need to give root permissions to the docker container, in order to access write operations on db.

**Comment by hassanmirseo** [comment]
I've installed it on localhost. Can you guide me further accordingly?

**Comment by cypris75** [comment]
Same issue after fresh install via [Cloudron](https://www.cloudron.io/store/com.serpbear.cloudronapp.html):

![image](https://github.com/user-attachments/assets/c45231ad-bf06-4236-953c-b7eeb97413f2)

**Comment by gramakri** [comment]
Cloudron package maintainer here. You have to enter URLs and not domain (yes, despite what the UI says) . Try adding `https://example.com` and it probably works.

See https://github.com/towfiqi/serpbear/blob/c5714c00aec31132d7a95f54624988269c404424/components/domains/AddDomain.tsx#L24 for the validation logic

**Comment by towfiqi** [comment]
Yes, it should be a website URL, not a domain. Serpbear initially only allowed adding domains, but few updates ago it was changed to URL instead, that's why the UI is a little confusing. I am considering changing the word Domain(s) to Website(s).

**Comment by cypris75** [comment]
I could have sworn that I tried every variation incl. the `https://...` one. But I just tried again and now it works. Thanks for the help! Adding an example / placeholder could help future users like me.

**Comment by towfiqi** [comment]
fixed slight UI change to alleviate this with 17fb2c40cc6b57ab2fe6aeb940dececd1a83411f
