### ISSUE TITLE
Possible error in CTR calculation

### ISSUE THREAD

**Issue by amedcalf** [towfiqi/serpbear#233]
Hi, thanks for this amazing tool! Just exploring everything it does now.

I think there's a bug with how it calcuates CTR on the "Insight" tab. I'm seeing CTR of e.g. 648% whereas I'd assume it should be <=100%.

I'm not certain but looking at the numbers I think it might be calculating "Impressions / Avg Position" instead of "Visits/Impressions".

Thanks again.

**Comment by lidarbtc** [comment]
CTR calculation is incorrect.

![스크린샷 2024-10-26 20-56-01](https://github.com/user-attachments/assets/391a40bd-507e-400a-b323-63f4b157e388)

My guess is that it summed each CTR to get an average, but then didn't divide them.
