### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by JvB94** [towfiqi/serpbear#236]
I see that some issues are open here and nobody cares. Is the project still being maintained?

**Comment by ingeniumdesign** [comment]
new project updates?

**Comment by chester-e** [comment]
> still works though

yeah but got bugs as well. would be nice if we would know if this will be getting future updates or not so we can stick or look for something else. would be a shame tho, love serpbear

**Comment by towfiqi** [comment]
Yes. However, if there are no critical bugs, each update may take 3-4 months when I have time in my busy schedule. The last update was around 7 months ago. So expect a new update within a few days.
