### ISSUE TITLE
Ability to switch between scraping method but keep API?

### ISSUE THREAD

**Issue by leonguyen52** [towfiqi/serpbear#28]
Hi, is there any chance to make it save API while we switch between different scraping service? I must input API again if I switch scraping method.

Btw, can you consider to add SerAPI to scraping method since I found out that their service is much more correct than ScrapingAnt, although their free limit is quite low but quality is better.

Thank you!

**Comment by towfiqi** [comment]
@leonguyen52 The way the app settings was written, its not possible to change the settings without breaking everyone's settings. Sadly you will have to switch and insert the API key everytime.

And SerpApi is also being worked on by the SerpApi team for the app.
