### ISSUE TITLE
Problem with custom proxies.

### ISSUE THREAD

**Issue by darorck** [towfiqi/serpbear#33]
With local proxies I get all the urls as this:
[/url?esrc=s&q=&rct=j](http://localhost:3000/url?esrc=s&q=&rct=j)

Fixed this by changing the scraper.ts file and using this headers instead:
`
   const proxy_headers: any = {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
      Accept: 'gzip,deflate,compress;',
   };
`

With this it works but I have some problems with the character encoding.

**Comment by towfiqi** [comment]
> With this it works but I have some problems with the character encoding.

Can you please share the scrape result with the bad encoding?

**Comment by darorck** [comment]
This is the normal behaviour, the urls don't parse correctly.
![0ef1cc1280392bbe5f49fd3d8d2f141c](https://user-images.githubusercontent.com/2346304/208269754-768f9d3b-dd20-4887-af0c-20b2d5cae10c.png)
This is what happens after changing the headers.
![534b86cf9c366d74a6e14d7b8e8ce9a3](https://user-images.githubusercontent.com/2346304/208269779-7b161c84-e6ee-4772-b3e2-12573c3692bf.png)

Thanks. Great project btw!

**Comment by towfiqi** [comment]
Fixed the issue. Before pushing the fix, I need your help. Can you please open the `sceaper.ts` file and replace line 181:
`const cleanedURL = url ? url.replace('/url?q=', '').replace(/&sa=.*/, '') : '';`

with this and see if that fixes the issue for you as well:
`const cleanedURL = url ? url.replaceAll(/^.+?(?=https:|$)/g, '').replaceAll(/(&).*/g, '') : '';`

Thanks

**Comment by darorck** [comment]
Works perfect now!. Just with this change all works correctly. Thanks a lot.
