### ISSUE TITLE
Invalid domain

### ISSUE THREAD

**Issue by lionep** [towfiqi/serpbear#4]
Hello,

After seeing issue #1 I've found a valid domain that is rejected by the regex : 
99.lc (I've a similar one).

Not all TLDs allow full digits domains, but some does.

Thanks !

**Comment by towfiqi** [comment]
Its actually the same bug. Just checked and the updated regex considers `99.lc`  as a valid domain.

I am guessing you are using docker. I forgot to push the updated image to docker hub. Just pushed it few minutes. Try pulling the image now.

Thanks

**Comment by lionep** [comment]
Indeed ! now fixed on my docker instance.
Thanks
