### ISSUE TITLE
permission denied error on Docker-compose deploy

### ISSUE THREAD

**Issue by woutr-nl** [towfiqi/serpbear#40]
When running the docker container i get the error:

`today at 10:20:30[1] node:internal/process/promises:288
today at 10:20:30[1]             triggerUncaughtException(err, true /* fromPromise */);
today at 10:20:30[1]             ^
today at 10:20:30[1] 
today at 10:20:30[1] [Error: EACCES: permission denied, open '/app/data/settings.json'] {
today at 10:20:30[1]   errno: -13,
today at 10:20:30[1]   code: 'EACCES',
today at 10:20:30[1]   syscall: 'open',
today at 10:20:30[1]   path: '/app/data/settings.json'
today at 10:20:30[1] }
today at 10:20:30[1] 
today at 10:20:30[1] Node.js v18.12.1
today at 10:20:30[1] node cron.js exited with code 1
today at 10:20:30[0] Listening on port 3000`

This is my docker-compose.yml:

`version: "3.8"

services:
  app:
    image: towfiqi/serpbear
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - USER=wouter
      - PASSWORD=#########
      - SECRET=4715aed3216f7b0a38e6b534a958362654e96d10fbc04700770d572af3dce43625dd
      - APIKEY=5saedXklbslhnapihe2pihp3pih4fdnakhjwq5
      - NEXT_PUBLIC_APP_URL=https://serpbear.woutr.io:3000
    volumes:
      - ./serpbear_appdata:/app/data
    labels:
      - "traefik.http.routers.serpbear.rule=Host(`serpbear.woutr.io`)"
      - "traefik.http.routers.serpbear.tls=true"
      - "traefik.http.routers.serpbear.tls.certresolver=lets-encrypt"
      - "traefik.http.services.serpbear.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    networks:
      - web

networks:
 web:
  external: true`

I'm not able to log in or anything so the DB is indeed not functioning.
What am i doing wrong?

**Comment by towfiqi** [comment]
Can you please try the methods described here: https://github.com/towfiqi/serpbear/discussions/22

**Comment by balonchiks** [comment]
i had the same issue, apparently your `./serpbear_appdata` folder should have all write access (777)

**Comment by Leopere** [comment]
This seems off to me, I think your container should impose file permissions for you on container instantiation if this is the case.

**Comment by TheZoker** [comment]
Same issue for me....
