### ISSUE TITLE
Unable to add scrapper

### ISSUE THREAD

**Issue by navendu-pottekkat** [towfiqi/serpbear#45]
I'm unable to add the token for both Scrapping Robot and ScrappingAnt. The token is correct, and it is not clear what the issue is.

This is what happens when I click submit:

<img width="303" alt="Screenshot 2022-12-25 at 11 25 19 AM" src="https://user-images.githubusercontent.com/49474499/209458346-315abcd7-6e81-4677-9431-fa5a37a09b6f.png">

I followed this guide and deployed it to fly.io: https://docs.serpbear.com/deployment/deploying-to-fly.io-free

**Comment by towfiqi** [comment]
Fixed. Please try again with the latest release.

**Comment by navendu-pottekkat** [comment]
Thanks, @towfiqi, it seems to work now. A popup or another type of notification to indicate success might be helpful.

**Comment by towfiqi** [comment]
Good call. Will do that in next release.

**Comment by AmsellemJoseph** [comment]
@towfiqi hey, I have the same probleme with the docker-compose installation.
I followed this guide: https://docs.serpbear.com/deployment/running-locally-with-docker#using-docker-compose
Thanks for your reply.

**Comment by towfiqi** [comment]
@AmsellemJoseph did you pull the latest release?

**Comment by AmsellemJoseph** [comment]
yes, sure
![Screen Shot 2022-12-28 at 19 06 50](https://user-images.githubusercontent.com/79039145/209847466-7e002305-1b95-49f6-a3a2-8fe57f9adbe3.png)

**Comment by towfiqi** [comment]
Can you please clear the browser cache and see if that fixes the issue?

**Comment by AmsellemJoseph** [comment]
> 

No, same thing
