### ISSUE TITLE
Most Viewed/Visited sorts in the wrong direction 

### ISSUE THREAD

**Issue by goaround** [towfiqi/serpbear#46]
If you sort the keywords in the Tracking tab, Most Viewed/Visited is sorts `asc` but should be `desc`

See: https://github.com/towfiqi/serpbear/blob/457f55353f61308f74faa1898a3be51c5b4c43c3/components/keywords/KeywordFilter.tsx#L85

**Comment by goaround** [comment]
Top Position and Lowest Position sorts in the wrong direction, too.

**Comment by towfiqi** [comment]
@goaround Just checked, and both works fine. Since the lower the position, the better it is, Top position sort displays the lowest ranks first.

**Comment by vontainment** [comment]
Yes, but in the tracker view its the opposite. They both should sort under the same idea.

**Comment by towfiqi** [comment]
Just checked, the Console View actually has the buggy behavior. Will fix in next release.

**Comment by goaround** [comment]
Tracking Top Position and Lowest Position sort are also wrong:

![UjXaIWm9](https://user-images.githubusercontent.com/5927337/211525369-e43068ca-256a-4637-95df-e45a4c9b2faf.png)

**Comment by towfiqi** [comment]
@goaround Thanks for that. Not sure how I missed it..
