### ISSUE TITLE
Only track specific pages (instead of the entire domain)

### ISSUE THREAD

**Issue by mihaicirstea** [towfiqi/serpbear#53]
It would be great if there was the option to track a specific page rather than the entire domain.

Do you see any work-arounds for this?

**Comment by mihaicirstea** [comment]
Also is the Mobile tracker supposed to work? Because I'm not seeing any mobile rankings collected - they're all blank. 
I'm using Scraping Robot API.

**Comment by towfiqi** [comment]
> It would be great if there was the option to track a specific page rather than the entire domain.

Sorry, that m,ight not be possible.



> Also is the Mobile tracker supposed to work? Because I'm not seeing any mobile rankings collected - they're all blank. I'm using Scraping Robot API.

Which Country? Some scrapers have weeak proxy ips for certain countries. For example, when you use ScrapingAnt to get rank of a keyword using the country india, most of the time it fails. 
Can you please try the same keyword you added for United States, and see if it fetches the rank?

**Comment by mihaicirstea** [comment]
> > It would be great if there was the option to track a specific page rather than the entire domain.
> 
> Sorry, that m,ight not be possible.

Can you explain why not? Because it seems to me it would be fairly simple by allowing the user to input the URL (instead of the domain) in the "Add Site". I tried this by modifying the domain in the database but then the tracker doesn't work. I guess something in the code is looking for only the domain?... Do you think it would be difficult to modify the system logic to allow for this flexiblity?
 
> > Also is the Mobile tracker supposed to work? Because I'm not seeing any mobile rankings collected - they're all blank. I'm using Scraping Robot API.
> 
> Which Country? Some scrapers have weeak proxy ips for certain countries. For example, when you use ScrapingAnt to get rank of a keyword using the country india, most of the time it fails. Can you please try the same keyword you added for United States, and see if it fetches the rank?

I was using UK before, but I tried United States as you advised but the same problem - nothing fetches even though it says keywords refreshed. I don't think it's a problem with the Scraping Robot API...

<img width="1073" alt="Screen Shot 2023-01-11 at 8 35 33 AM" src="https://user-images.githubusercontent.com/10725789/211819885-af885c26-3595-4399-8ff7-e432e3ab44e5.png">
<img width="996" alt="Screen Shot 2023-01-11 at 8 34 57 AM" src="https://user-images.githubusercontent.com/10725789/211819889-1b93e1dd-5a1a-46e1-8d39-db7649297d14.png">

Thank you!

**Comment by Frooodle** [comment]
+1 on specific URL tracking, i want to track
https://github.com/Frooodle/Stirling-PDF
but can only track github.com
