### ISSUE TITLE
Deploying to Fly.io

### ISSUE THREAD

**Issue by Dan4ic** [towfiqi/serpbear#56]
Hi
Hi...did anyone have any luck with the deployment of as instructed?
https://docs.serpbear.com/deployment/deploying-to-fly.io-free
 
For the 2nd day i can't get it set up...

**Comment by towfiqi** [comment]
What step of the deplyoment process are you stuck at?

**Comment by Dan4ic** [comment]
> What step of the deplyoment process are you stuck at?

Step 5:
Open the newly created fly.toml file in your serpbear directory and add this to the very bottom to connect the newly created volume to your app. 

I can't figure it out...it says to open the created file "fly.toml", but it was not created earlier in the directory "serpbear" in step 4
I.e., this file is not in the folder "serpbear"

Step 3 and 4 (screenshot):
https://skr.sh/sHq3rwjdpDZ

**Comment by towfiqi** [comment]
@Dan4ic Its not working because you did not enter the serpbear directory. You need to enter your local serpbear directory and then run the commands described in the documentation. Check the step 2 of the documentaiton. You will need to clone the serpbear git repo first and then cd into the cloned serpbear directory. 

And Since you fly command did not find any docker file to create the project from it created an app with a blank template. So your current fly.io project is a blank app. You can remove it.

**Comment by Dan4ic** [comment]
@towfiqi  Thank you for your reply.
Step 1 and 2 previously made, did not want to write about, then continued with the problematic.

In general, started at the beginning. I'll try to go over the points with you)

Step ...2 and 3 and 4 
https://skr.sh/sHqdyfjzcP0
right?

**Comment by towfiqi** [comment]
There should be an output when you run the fly launch command. Can you please check your fly dashboard and see if the app was created or not? Also, check if the fly.toml was created inside the serpbear folder.

**Comment by Dan4ic** [comment]
> There should be an output when you run the fly launch command. Can you please check your fly dashboard and see if the app was created or not? Also, check if the fly.toml was created inside the serpbear folder.

Fly.io:
https://skr.sh/sHqzZXkpwwZ
P/S. I deleted all the previous ones. (app)

Serpbear folder, no file "fly.toml" :
https://skr.sh/sHqK1gfH1Kh

**Comment by towfiqi** [comment]
Can you please delete the current app and try again? And when you launch the app with fly launch command, it should output that the deplyment was successful. You should only move forward if you get an output after running that command.

**Comment by Dan4ic** [comment]
@towfiqi 
I've already deleted all the applications.
In general, already confused in all this. Again removed all and everything and the folder. Let's start from scratch)

Let's go with you step by step)
What are the first things I need to do...?

**Comment by towfiqi** [comment]
Ok. First follow these crucial steps:

1. Opne the command prompt, and run this command:
`git clone git@github.com:towfiqi/serpbear.git`

2. Then, enter into the newly created serpbear folder by running:
`cd serpbear`

3. Then deploy the app to fly.io by running this command:
`fly launch --name mysolarperks --region lax`

Once you run this commnad, you should see a success mesaage. Something like this:
```
Created app mysolarperks  in  organization personal....
Admin url:  https://......
Hosname: ....
Wrote Config file fly.toml
```

If you dont get this message, you should recieve an error at-lease share what error you recieved. If you get the success message, make sure there is a fly.toml file inside the sperbear directory.

**Comment by Dan4ic** [comment]
3 steps successfully passed:
https://skr.sh/sHsrXmHqCW1

Next...)

**Comment by towfiqi** [comment]
Not sure whats happening. Can you please search your whole pc for that fly.toml file

**Comment by Dan4ic** [comment]
Yes did a full search, no such file.
Maybe it can't be created because of the operating system, i.e. maybe there are restrictions...?
I have Windows 10 x64

**Comment by towfiqi** [comment]
That's not an issue. I am using fly on windows 10 without any issues.
Can you please open power shell as administrator, and then run the command inside the powershell.

**Comment by Dan4ic** [comment]
Tried to disable the antivirus and the file was created)
https://skr.sh/sHtAyfGLqzc

What are the next steps...?

**Comment by towfiqi** [comment]
Now you can follow from step 4 from the documentation: https://docs.serpbear.com/deployment/deploying-to-fly.io-free

**Comment by Dan4ic** [comment]
Is step 5 correct in the file...?
https://skr.sh/sHtB75fuFKv

**Comment by Dan4ic** [comment]
Got it, deployed the applications already)

Thank you for your help.
Have a nice day!

**Comment by towfiqi** [comment]
Great to hear that!
