### ISSUE TITLE
ScrapingRobot Mobile Tracker Not working 

### ISSUE THREAD

**Issue by towfiqi** [towfiqi/serpbear#58]
Also is the Mobile tracker supposed to work? Because I'm not seeing any mobile rankings collected - they're all blank. 
I'm using Scraping Robot API.

_Originally posted by @mihaicirstea in https://github.com/towfiqi/serpbear/issues/53#issuecomment-1371822567_

**Comment by mihaicirstea** [comment]
@towfiqi The fix did not solve the problem.

**Comment by towfiqi** [comment]
@mihaicirstea Just tested again and it worked fine. Took a long time, but it worked..
Your keyword's country is set to UK?

**Comment by towfiqi** [comment]
Also, after refreshing the keyword, click the Keyword to open the detail view, and check the search result and see if the domain appears in the search result.

**Comment by mihaicirstea** [comment]
@towfiqi Yes I tested UK & US and none work. See: https://www.loom.com/share/20692bac70e441289c2f68539dc82299
Notice the search results are blank which I guess means the data from Scraping Robot API is not coming through.

**Comment by towfiqi** [comment]
@mihaicirstea Just tried with same domian and keyword on my installation and it worked fine. https://i.imgur.com/3wiMPNa.png

Can you please make sure you have pulled the latest docker image?

**Comment by mihaicirstea** [comment]
@towfiqi I did pull the update from the github repository, but I'm not using docker. I just setup locally on my Mac for testing.
