### ISSUE TITLE
No position with www. domain

### ISSUE THREAD

**Issue by xlnd47** [towfiqi/serpbear#6]
Hi! 

Really great project!
Here is a problem I encountered. I added a domain "vtideinze.be" added some keywords and it found the site on position 4.
But the position did not update on the dashboard. 

![image](https://user-images.githubusercontent.com/26673889/205003738-74c976cc-d798-4e1e-aeb4-ebca6e078364.png)

**Comment by towfiqi** [comment]
Looks like a bug. Will be fixed shortly. Thanks for pointing it out.

**Comment by towfiqi** [comment]
@lionep Just added your domain and the keyword on my app instance and not seeing your site on first 100 results. 

You can click the keyword to see the detail view and check the latest search result to see if your domain appears in it.

**Comment by lionep** [comment]
@towfiqi after a quick investigation, the result is ok in the html returned by the scraping api (domain present in the first item). It might be a parsing issue?

**Comment by towfiqi** [comment]
@lionep Can you please share the screenshot of the search result you are seeing, on my instance, I could not find your domain for "Sucrine club" keyword.
