### ISSUE TITLE
Feat: Ability to move keywords to mobile tab without copy and paste

### ISSUE THREAD

**Issue by Cliftonz** [towfiqi/serpbear#60]
Currently to get keywords that are placed in desktop in the mobile tab, I have to manually copy the whole list to the mobile tab

It would be great to have some functionality that would allow you to easily send a keyword to mobile or desktop from the other tab.

**Comment by ingeniumdesign** [comment]
+1

If you add a keyword, you could also have the option, create in mobile and desktop.

**Comment by saschafoerster** [comment]
I would even say, make "mobile and desktop" the default. Also choosing a single default language might be nice.
