### ISSUE TITLE
Keyword refresh stuck

### ISSUE THREAD

**Issue by rsebi** [towfiqi/serpbear#69]
Running on latest Docker pull, keyword is endlessly on refresh job. Any attempt to force a refresh will make the instance non responsive.
Having about 30 keywords to track for a single domain.

<img width="234" alt="Screenshot_197" src="https://user-images.githubusercontent.com/102179977/213795323-9ac9a5c3-9685-4168-807f-f31b152c1dda.png">

OS: Ubuntu 20.04.5 LTS
Version:

**Comment by towfiqi** [comment]
@rsebi which scrapper are you using? Can you please check the log?

**Comment by rsebi** [comment]
@towfiqi I am using scrappingant and since 12th Jan there is no usage.

**Comment by towfiqi** [comment]
Can you please try with ScrapingRobot?

**Comment by rsebi** [comment]
Tried and getting same result (loading). The app is going into non-responsive mode like before. With forcing me to restart container to bring the webui back.

**Comment by towfiqi** [comment]
@rsebi How often does this freezing behaviro happens? Does it happens when it tries to run the CRON? Did you check the log? Also, let me know how and where you are running the app.

**Comment by rsebi** [comment]
@towfiqi Initially the issue used to be when it scraps for update so i got around it by updating one keyword at time manually, however since the reported issue, the whole app goes unresponsive even after a restart and is stuck at refresh icon and eventually crashing the webui.

Can you tell me how to check the log in docker setup.

Running on Ubuntu 20.04 LTS and on latest docker pull.

**Comment by towfiqi** [comment]
@rsebi Can you please go to the data folder and check the size of the `database.sqlite` file. If it more than 1-2 megabytes, most probably the database got corrupted somehow.

**Comment by rsebi** [comment]
It looks like that's the case, the size is 333M. Should i start over or simply delete the file to reset?

**Comment by towfiqi** [comment]
You can acutally, clean/optimize the databse to fix the issue. 
First Download Sqlite Browser. https://sqlitebrowser.org/dl/ 
Then open the `database.sqlite` file in it. 
Then click the "Execute SQL" tab.
And insert this command: `VACUUM;`
And click the play button to run the command.
Once its done, the file size should be reduced to few hundred kilobytes. 

If it doesn't. You will have to move the existing `database.sqlite` from the databse and then start the app and a new sqlite file will be created and you will have to start over.

**Comment by rsebi** [comment]
Ended up deleting the database however now the keywords does not show any ranking at all. Although it looks like the interface is working and checking ranking. 
Should we give it sometime?

**Comment by towfiqi** [comment]
@rsebi When you manually refresh the keywords, they should show up withina  few seconds. Can you please check the docker container log and see if there are any errors?

**Comment by rsebi** [comment]
It does not show any result and api does not show usage either. I ended up destroying the vm and setting it up again but did not get chance to fully set it up. Update to follow.

**Comment by rsebi** [comment]
Finally redeployed and everything working as expected. 
Only issue encountered was scrapingant api no longer works.
