### ISSUE TITLE
[feat req] Add Webshare proxy list format

### ISSUE THREAD

**Issue by rastarr** [towfiqi/serpbear#70]
Hi,
I use Webshare proxies and their API

[1] Is it possible to make this feature work to pull down my current list of proxies?
[2] Can this refresh the list each day SerpBear runs as well since these proxies rotate every 7 days

Format is https://proxy.webshare.io/api/v2/proxy/list/download/My-API-KEY-GOES-HERE/-/any/username/direct/-/

Awesome work on SerpBear too BTW - great project and thank you

**Comment by towfiqi** [comment]
@rastarr Webshare already has a rotating proxy feature that lets you use a random proxy from your proxy pool with just one link. To use that rotating proxy link follow thesee steps:

- Go to your webshare account, then to "Rotating Proxy', and then click the "See Example Configurations" link. 
- This will open up a popup with various methods of implentating the rotating proxy. 
- From the "Curl" tab, copy the link inside the double qoutes. It will look something like this:
`http://eixxtqm-rotate:maejiahx78la@p.webshare.io:80/`
- Then go to you SerpBear's Proxy Settings option and inside the proxy field, insert the copied link without the trailing slash. Like so: `http://eixxtqm-rotate:maejiahx78la@p.webshare.io:80` . 
- Update the settings, refresh the page. 

Now when a Serpbear makes a request using that link, webshare will redirect the link to one of your ips randomly.

**Comment by rastarr** [comment]
Thanks for that
Sadly, I get the following error-
"Error Updating Keyword position (Tried 30 seconds ago)
Proxy: [429] Too Many Requests"

**Comment by towfiqi** [comment]
@rastarr thats the issue with webshare, their ips are frequently used for google scraping. Hence google keep temporarirly blocking them with "Too Many Requests". You can keep trying couple of times, and one of the ips should be able scrape the keyword positions.

**Comment by rastarr** [comment]
Ahh ok gotcha and thanks
Switched to Scraping Robot for the time being.
Thanks so much for the help
