### ISSUE TITLE
Keyword Tracking Intervals? 

### ISSUE THREAD

**Issue by daninelson** [towfiqi/serpbear#76]
Is it possible to set custom interval scan times? If not, perhaps it can be added as a feature. Rather than it scanning my keywords every single day and using up my serp credits. 

Like an option in the settings to select between daily, weekly, monthly auto scans.

**Comment by towfiqi** [comment]
@daninelson Will try to add this feature in next release. Thanks for the suggestion. It has been asked a few times.
