### ISSUE TITLE
Scraping Ant does not work anymore

### ISSUE THREAD

**Issue by L4ma** [towfiqi/serpbear#78]
Hi,
I have been using Scraping Ant all the time, but a few days ago I got the message: "This domain no longer works with Scraping Ant, please upgrade your account". I actually still have enough free scrapes. 

Can anyone help me with this?

**Comment by towfiqi** [comment]
@L4ma Yes, they are blocking their free service from scraping google becuase Google bans ips when they are detected. Its bad for their business. For now, our best bet is scrapingrobot.
