### ISSUE TITLE
[BUG] "Keywords added successful" with no keywords beeing shown

### ISSUE THREAD

**Issue by justuspfaue** [towfiqi/serpbear#8]
Hey, first of all, thanks for this awesome project!

Unluckily I have a problem where I can't add keywords. I spun up the project with the example compose and left the values as standart (on the first try i changed the key and password and so on). Then I went into the settings and added the API key for the scrapper (this works, as everytime I "add" a keyword, the count of requests on the scraper site ticks up!)

But I can neither view them in the WEBUI nor in the "api" (/api/...) in the browser (different browsers). It does show my domains, but not my keywords.

From the logs:

> [1] Error: Settings file dont exist.
> [1]     at getAppSettings (/app/cron.js:34:16)
> [0] Listening on port 3000
> ...
> [0] GET /api/keywords?domain=DOMAINNAME
> [0] getKeywords:  0
> [0] SERP:  KEYWORD 0 
> [0] ALL DONE!!!
> [0] time taken: 6722.727298736572ms
> [0] [Error: ENOENT: no such file or directory, open '/app/data/failed_queue.json'] {
> [0]   errno: -2,
> [0]   code: 'ENOENT',
> [0]   syscall: 'open',
> [0]   path: '/app/data/failed_queue.json'
> [0] }
> [0] [SUCCESS] Updating the Keyword:  KEYWORD
> [0] GET /api/domains
> [0] GET /api/keywords?domain=DOMAINNAME
> [0] getKeywords:  0

I can see the request in the browser as well as an successful answer from the backend. I am also able to see that there is in fact data in the DB (per "cat" on the server).

I hope this helps. If you need any other information, I will gladly take another look into the logs.

**Comment by towfiqi** [comment]
@justuspfaue Sounds like the issue is actually on the frontend. Can you please check the browser console log and see if there are any errors once you submit the Add Keyword Modal?

**Comment by memarius** [comment]
Hi @towfiqi,
I just installed it via docker and am encountering the same problem as op.
When looking at the browser console there are no errors.
1. Adding Keywords: POST Request to /api/keywords comes back as 200 ok, payload looks okay too (has all the keywords and no error)
2. In the container's log I can see that the added keywords have been successfully updated
3. After reloading the page for the domain, the request to fetch the domains comes back as 200 with `{"keywords":[]}` as payload and the backend log says `[0] GET /api/keywords?domain=[redacted]` and `[0] getKeywords:  0`

**Comment by establishedweb** [comment]
Having the same issue. I've noticed that I'm only seeing these errors on domains that have "www."

**Comment by towfiqi** [comment]
@establishedweb Thanks for that. Just spotted the bug. Will push the fix shortly.

**Comment by towfiqi** [comment]
@justuspfaue You are not unlucky. Its the same bug, but it occurs for domains with hyphens. Will be fixed shortly.

**Comment by justuspfaue** [comment]
It's fixed now. Thanks!
