### ISSUE TITLE
Setting for cron-jobs

### ISSUE THREAD

**Issue by Mobilpadde** [towfiqi/serpbear#81]
I'd love if it didn't run the scraper everyday, I would much rather have a every three days or so, and get an email after it's completed - so no need for the custom email notifications-job either :smiling_face_with_tear: 

Would this be possible?

A side-note: I love SerpBear, it's easy to use and set-up. Thanks! :star_struck:

**Comment by Mitsu66** [comment]
I agree, if we could choose between daily, weekly, or monthly scraping, that would be perfect.
Btw thank you, this application is awesome !

**Comment by PierreClementCazon** [comment]
I agree. Particularly useful to be able to switch to one run per week to avoid using all the free API credits before the end of each month.
