### ISSUE TITLE
Delay Requests

### ISSUE THREAD

**Issue by abhranil26** [towfiqi/serpbear#87]
Which file do I have to modify to delay the requests? My proxy gives Too Many requests error alot.

**Comment by towfiqi** [comment]
delay between each keyword scrape when daily scrape runs?

**Comment by abhranil26** [comment]
Yeah, is that possible?

**Comment by towfiqi** [comment]
Just added a delay option. Pull the latest release and you will find the delay option inside the Settings panel.

**Comment by abhranil26** [comment]
Thank you, works, great now.
ধন্যবাদ
