### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by abhranil26** [towfiqi/serpbear#89]
Hi,
It would be great if the best position of the keyword was also shown like it is shown in serprobot.
![image](https://user-images.githubusercontent.com/30792751/227780059-7ba9739a-6c06-4499-97fa-dd6265bfb44b.png)

**Comment by sumitguptaji** [comment]
+1 for this feature. As well as an chart like this will make it perfect overall. 
![Uploading Screenshot_20230326_202222_Chrome.jpg…]()

**Comment by sumitguptaji** [comment]
![Screenshot_20230326_202222_Chrome](https://user-images.githubusercontent.com/35533649/227784071-2e076139-949d-4730-b4f5-4a88c2d81fa1.jpg)
